package com.localapartmentexperts.crm.common.enums;

public enum ActivityType {
    LEAD_CREATED,
    LEAD_UPDATED,
    STATUS_CHANGED,
    NOTE_ADDED,
    ASSIGNED,
    FOLLOW_UP_SET,
    CONTACT_METHOD_UPDATED,

    PROPERTY_CREATED,
    PROPERTY_UPDATED,
    PROPERTY_PUBLISHED,
    PROPERTY_UNPUBLISHED,
    PROPERTY_ARCHIVED,

    PROPERTY_IMAGE_UPLOADED,
    PROPERTY_IMAGE_DELETED,
    PROPERTY_IMAGE_COVER_CHANGED,
    PROPERTY_IMAGE_REORDERED,

    PROPERTY_LINKED,
    PROPERTY_LINK_UPDATED,
    PROPERTY_UNLINKED
}
